# Area quality tiers: P=Prime, E=Established, M=Mid-Tier, X=Peripheral
AREA_TIERS = {
    # Dubai
    "DIFC": "P",
    "Palm Jumeirah": "P",
    "Downtown Dubai": "P",
    "Dubai Marina": "E",
    "Jumeirah": "P",
    "Jumeirah Lake Towers": "E",
    "Business Bay": "E",
    "Bluewaters": "P",
    "Al Sufouh": "E",
    "Dubai Hills Estate": "E",
    "Mohammed Bin Rashid City": "E",
    "Dubai Creek Harbour": "E",
    "Jumeirah Village Circle": "M",
    "Jumeirah Village Triangle": "M",
    "Al Furjan": "M",
    "Dubai South": "M",
    "Dubai Sports City": "M",
    "Discovery Gardens": "M",
    "International City": "X",
    "Dubai Silicon Oasis": "M",
    "Dubai Investment Park": "X",
    "Arjan": "M",
    "Motor City": "M",
    "Town Square": "M",
    "DAMAC Hills": "M",
    "Damac Hills 2": "M",
    "Greens": "E",
    "The Views": "E",
    "Barsha Heights (Tecom)": "E",
    "Al Barsha": "M",
    "Bur Dubai": "E",
    "Al Jaddaf": "M",
    "Dubai Festival City": "E",
    "Culture Village": "E",
    "City Walk": "P",
    "Dubai Harbour": "E",
    "Meydan": "E",
    "Dubai Studio City": "M",
    "Dubai Production City": "M",
    "Dubai Science Park": "M",
    "Al Quoz": "M",
    "Al Satwa": "M",
    "Al Muhaisnah": "X",
    "Al Warsan": "X",
    "Nadd Al Hammar": "X",
    "Dubai Land": "M",
    "Mudon": "M",
    "Hartland Greens": "E",
    "Living Legends": "M",
    "Maritime City": "M",
    "Downtown Jebel Ali": "M",
    "Jebel Ali": "M",
    "Wadi Al Safa": "M",
    "Wasl Gate": "M",
    "JBR": "P",
    "Umm Suqeim": "E",
    # Abu Dhabi
    "Al Reem Island": "E",
    "Yas Island": "E",
    "Saadiyat Island": "P",
    "Al Maryah Island": "P",
    "Al Raha Beach": "E",
    "Al Ghadeer": "M",
    "Al Reef": "M",
    "Masdar City": "E",
    "Khalifa City": "M",
    "Al Jubail Island": "E",
    "Mohamed Bin Zayed City": "M",
    "Al Khalidiya": "E",
    "Corniche Road": "P",
    "Al Bateen": "P",
    "Baniyas": "X",
    "Al Shamkha": "X",
    "Al Mushrif": "M",
    "Madinat Al Riyad": "M",
    "Al Danah": "E",
    "Al Nahyan": "M",
    "Hamdan Street": "E",
    "Muroor Area": "M",
    "Airport Road": "M",
    "Tourist Club": "E",
    "The Marina": "E",
    "City Downtown": "E",
    "Mussafah": "X",
    "Al Wahda": "M",
    "Rawdhat": "M",
    "Al Zahiyah": "E",
    "Electra Street": "M",
    "Capital Centre": "M",
    "Al Falah City": "X",
    "Rabdan": "E",
}

DEFAULT_TIER = "M"

SERVICE_CHARGE_BY_AREA = {
    # Dubai
    "DIFC": 25, "Palm Jumeirah": 22, "Downtown Dubai": 24, "City Walk": 26,
    "Bluewaters": 28, "JBR": 22, "Jumeirah": 20, "Dubai Marina": 18,
    "Business Bay": 17, "Jumeirah Lake Towers": 15, "Dubai Hills Estate": 16,
    "Mohammed Bin Rashid City": 17, "Dubai Creek Harbour": 18, "Al Sufouh": 16,
    "Greens": 16, "The Views": 16, "Barsha Heights (Tecom)": 14, "Bur Dubai": 13,
    "Dubai Festival City": 17, "Culture Village": 16, "Dubai Harbour": 19,
    "Meydan": 15, "Hartland Greens": 16, "Jumeirah Village Circle": 12,
    "Jumeirah Village Triangle": 12, "Al Furjan": 13, "Dubai South": 11,
    "Dubai Sports City": 12, "Discovery Gardens": 10, "Dubai Silicon Oasis": 12,
    "Arjan": 11, "Motor City": 13, "Town Square": 12, "DAMAC Hills": 14,
    "Damac Hills 2": 10, "Al Barsha": 13, "Al Jaddaf": 12,
    "Dubai Studio City": 12, "Dubai Production City": 10, "Dubai Science Park": 12,
    "Al Quoz": 11, "Al Satwa": 11, "Dubai Land": 11, "Mudon": 11,
    "Living Legends": 10, "Maritime City": 10, "Downtown Jebel Ali": 10,
    "Jebel Ali": 9, "Wadi Al Safa": 10, "Wasl Gate": 11,
    "International City": 9, "Dubai Investment Park": 8,
    "Al Muhaisnah": 9, "Al Warsan": 9, "Nadd Al Hammar": 9,
    "Umm Suqeim": 18,
    # Abu Dhabi
    "Al Reem Island": 16, "Yas Island": 15, "Saadiyat Island": 20,
    "Al Maryah Island": 22, "Al Raha Beach": 16, "Al Ghadeer": 10,
    "Al Reef": 10, "Masdar City": 14, "Khalifa City": 10,
    "Al Jubail Island": 13, "Mohamed Bin Zayed City": 9, "Al Khalidiya": 14,
    "Corniche Road": 18, "Al Bateen": 18, "Baniyas": 8, "Al Shamkha": 8,
    "Al Mushrif": 10, "Madinat Al Riyad": 9, "Al Danah": 14, "Al Nahyan": 10,
    "Hamdan Street": 12, "Muroor Area": 10, "Airport Road": 10,
    "Tourist Club": 12, "The Marina": 15, "City Downtown": 14,
    "Mussafah": 7, "Al Wahda": 10, "Rawdhat": 10, "Al Zahiyah": 12,
    "Electra Street": 10, "Capital Centre": 12, "Al Falah City": 7, "Rabdan": 14,
}

SERVICE_CHARGE_BY_TIER = {"P": 23, "E": 16, "M": 12, "X": 9}
DEFAULT_SC_PER_SQFT = 12
